# Generated by Django 3.0.6 on 2020-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='article',
            new_name='profile',
        ),
    ]
