# Generated by Django 3.0.6 on 2020-05-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200515_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies_list',
        ),
        migrations.AddField(
            model_name='comment',
            name='film',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='profile',
            name='films_list',
            field=models.ManyToManyField(to='main_app.Film'),
        ),
    ]
