# Generated by Django 3.0.6 on 2020-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200519_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_path',
            field=models.CharField(default='yes', max_length=200),
            preserve_default=False,
        ),
    ]
